#!/bin/sh -u

sysname=darwin
compiler=gcc

cp .gdbinit-$sysname src/.gdbinit
cp config-$sysname.hh include/config.hh
ln -s config-$sysname-$compiler.mk config.mk
ln -s config-$sysname.sh config.sh
pushd lib/dakota
ln -s compiler-$compiler.json compiler.json
ln -s platform-$sysname.json  platform.json
popd
