#!/bin/sh -u

sysname=linux
compiler=gcc

cp config-$sysname.hh include/dakota/config.hh
cp config-$sysname-$compiler.mk config.mk
cp lib/dakota/compiler-$compiler.json lib/dakota/compiler.json
cp lib/dakota/platform-$sysname.json  lib/dakota/platform.json
cp config-$sysname.sh config.sh
cp .gdbinit-$sysname src/.gdbinit
