#!/bin/bash
set -o nounset -o errexit -o pipefail

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

source $DIR/common.sh

rm -f config.sh
rm -f dakota-core/config.h
rm -f lib/dakota/compiler
rm -f lib/dakota/platform.json

if (( 0 == $# )); then
  exit
fi

sysname=$1
compiler=$2

source $DIR/config-$sysname.sh

$LN $LNFLAGS config-$sysname.sh config.sh

canon_compiler=$(compiler $compiler)
pushd lib/dakota > /dev/null 2>&1
$LN $LNFLAGS linker-$canon_compiler.opts   linker.opts
$LN $LNFLAGS compiler-$canon_compiler.opts compiler.opts
popd > /dev/null 2>&1

pushd lib/dakota/platform > /dev/null 2>&1
./configure
popd > /dev/null 2>&1
