#!/bin/sh -u

sysname=darwin
compiler=clang

cp config-$sysname.hh include/config.hh
cp config-$sysname-$compiler.mk config.mk
cp lib/dakota/compiler-$sysname-$compiler.pm lib/dakota/compiler.pm
cp config-$sysname.sh config.sh
cp .lldbinit-$sysname src/.lldbinit
