macros:
include-dirs:
  - ${source_dir}/include
lib-dirs:
libs:
target-path: ${bin_dir}/dakota-find-library${exe_suffix}
target-libs:
  - dakota-dso
target-type: executable
srcs:
  - dakota-find-library.cc
