# -*- mode: cmake -*-
set (CMAKE_VERBOSE_MAKEFILE $ENV{CMAKE_VERBOSE_MAKEFILE})
set (CMAKE_PREFIX_PATH ${prefix-dir})
include (${prefix-dir}/lib/dakota/functions.cmake)

current_build_dir (current-build-dir ${CMAKE_CURRENT_BINARY_DIR})
if (DEFINED use-binary-dir-as-build-dir OR DEFINED ENV{DKT_USE_BINARY_DIR_AS_BUILD_DIR})
  set (current-build-dir ${CMAKE_CURRENT_BINARY_DIR})
endif ()
if (NOT target-type)
  set (target-type executable)
endif ()

if (${target-type} STREQUAL shared-library)
  add_library (${target} SHARED ${srcs})
  set_target_properties (${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${prefix-dir}/lib)
  if (DEFINED install-include-files)
    install (FILES ${install-include-files} DESTINATION ${CMAKE_INSTALL_PREFIX}/include)
  endif ()
  install (TARGETS ${target} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
  set (target-output-file ${CMAKE_SHARED_LIBRARY_PREFIX}${target}${CMAKE_SHARED_LIBRARY_SUFFIX})
elseif (${target-type} STREQUAL executable)
  add_executable (${target} ${srcs})
  set_target_properties (${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${prefix-dir}/bin)
  install (TARGETS ${target} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
  set (target-output-file ${target}${CMAKE_EXECUTABLE_SUFFIX})
else ()
  message (FATAL_ERROR "error: target-type must be shared-library or executable.")
endif ()

find_lib_files (lib-files "${lib-dirs}" ${libs})
target_lib_files (target-lib-files ${target-libs})

if (DEFINED lib-files)
  target_link_libraries (${target} ${lib-files})
endif ()
if (DEFINED target-lib-files)
  target_link_libraries (${target} ${target-lib-files})
endif ()
if (DEFINED target-libs)
  add_dependencies (     ${target} ${target-libs})
endif ()

include (${prefix-dir}/lib/dakota/compiler-cxx.cmake)
