# -*- mode: cmake -*-
set (CMAKE_VERBOSE_MAKEFILE $ENV{CMAKE_VERBOSE_MAKEFILE})

function (opts_str values output-var)
  string (REPLACE ";" " " tmp-opts-str "${values}")
  set (${output-var} "${tmp-opts-str}" PARENT_SCOPE)
endfunction()

function (install_symlink file symlink)
  install (CODE "execute_process (COMMAND ${CMAKE_COMMAND} -E create_symlink ${file} ${symlink})")
  install (CODE "message (\"-- Installing symlink: ${symlink} -> ${file}\")")
endfunction ()

if (NOT target-type)
  set (target-type executable)
endif ()

if ("${target-type}" STREQUAL "shared-library")
  add_library (${target} SHARED ${srcs})
  set_target_properties (${target} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${dakota-lang-source-dir}/lib)
  install (TARGETS ${target} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
  set (target-output-file ${CMAKE_SHARED_LIBRARY_PREFIX}${target}${CMAKE_SHARED_LIBRARY_SUFFIX})
elseif ("${target-type}" STREQUAL "executable")
  add_executable (${target} ${srcs})
  set_target_properties (${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${dakota-lang-source-dir}/bin)
  install (TARGETS ${target} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
  set (target-output-file ${target}${CMAKE_EXECUTABLE_SUFFIX})
else ()
  message (FATAL_ERROR "error: target-type must be shared-library or executable.")
endif ()

set (lib-files)
foreach (lib ${libs})
  set (found-lib-file NOTFOUND) # found-lib-file-NOTFOUND
  find_library (found-lib-file ${lib} PATHS ${lib-dirs})
  if (NOT found-lib-file)
    message (FATAL_ERROR "error: target: ${target}: find_library(): ${lib}")
  endif ()
  #message ( "info: target: ${target}: find_library(): ${lib} => ${found-lib-file}")
  list (APPEND lib-files ${found-lib-file})
endforeach ()

set (target-lib-files)
foreach (lib ${target-libs})
  set (target-lib-file ${dakota-lang-source-dir}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}${lib}${CMAKE_SHARED_LIBRARY_SUFFIX})
  list (APPEND target-lib-files ${target-lib-file})
endforeach ()

set (compiler-opts @${dakota-lang-source-dir}/lib/dakota/compiler.opts)
set (linker-opts   @${dakota-lang-source-dir}/lib/dakota/linker.opts)
target_compile_options (${target} PRIVATE ${compiler-opts})
set (link-options ${linker-opts})
set (CMAKE_PREFIX_PATH  ${dakota-lang-source-dir})
#set (CMAKE_LIBRARY_PATH ${dakota-lang-source-dir}/lib)
set (cxx-standard 17)
set (CMAKE_COMPILER_IS_GNUCXX TRUE)

set (cxx-compiler NOTFOUND) # cxx-compiler-NOTFOUND
find_program (cxx-compiler clang++${CMAKE_EXECUTABLE_SUFFIX})
if (NOT cxx-compiler)
  message (FATAL_ERROR "error: program: clang++: find_library(): ${cxx-compiler}")
endif ()

set (CMAKE_CXX_COMPILER ${cxx-compiler})
set (compile-defns DKT_TARGET_FILE="${target-output-file}" DKT_TARGET_TYPE="${target-type}")
set_source_files_properties (${target-src} PROPERTIES COMPILE_DEFINITIONS "${compile-defns}")
if (target-dependencies)
  add_dependencies (${target} ${target-dependencies})
endif ()

install (FILES ${install-include-files} DESTINATION ${CMAKE_INSTALL_PREFIX}/include)
set (additional-make-clean-files
  ${build-dir}
)
set_directory_properties (PROPERTY ADDITIONAL_MAKE_CLEAN_FILES "${additional-make-clean-files}")
set_source_files_properties (${srcs} PROPERTIES LANGUAGE CXX CXX_STANDARD ${cxx-standard})
set_target_properties (${target} PROPERTIES LANGUAGE CXX CXX_STANDARD ${cxx-standard})
set_target_properties (${target} PROPERTIES CXX_VISIBILITY_PRESET hidden)
#set (CMAKE_CXX_VISIBILITY_PRESET hidden)
target_compile_definitions (${target} PRIVATE ${macros})
target_include_directories (${target} PRIVATE ${include-dirs})
opts_str ("${link-options}" link-options-str)
set_target_properties (${target} PROPERTIES LINK_FLAGS "${link-options-str}")
list (LENGTH lib-files len)
if (${len})
  target_link_libraries (${target} ${lib-files})
endif ()
list (LENGTH target-lib-files len)
if (${len})
  target_link_libraries (${target} ${target-lib-files})
  add_dependencies (     ${target} ${target-libs})
endif ()
