macros:
include-dirs:
  - ${source_dir}/include
lib-dirs:
libs:
target: dakota-catalog
target-path: ${bin_dir}/dakota-catalog${exe_suffix}
target-libs:
  - dakota-dso
target-type: executable
srcs:
  - dakota-catalog.cc
