macros:
include-dirs:
  - ${source_dir}/include
install-include-files:
  - ${source_dir}/include/dakota-dso.h
lib-dirs:
libs:
  - dl
target: dakota-dso
target-path: ${lib_dir}/${lib_prefix}dakota-dso${lib_suffix}
target-libs:
target-type: shared-library
srcs:
  - dakota-dso.cc
