macros:
bin-dirs:
  - ${source_dir}/bin
include-dirs:
  - ${source_dir}/include
lib-dirs:
libs:
target-path: ${source_dir}/tst1/exe${exe_suffix}
target-libs:
  - dakota-core
target-type: executable
srcs:
  - exe.dk
