all:
	./generate-compiler-default-argument-promotions.pl

install:
	cp compiler-default-argument-promotions.json ../../../lib/dakota

clean:
	rm -f type-index
	rm -f compiler-default-argument-promotions.json
