struct str_pair_t { char const* first; char const* last; };

static str_pair_t str_pair[] = {
  { .first = "fremescent", .last = "FREMESCENT" },
  { .first = "expletive", .last = "EXPLETIVE" },
  { .first = "martinetship", .last = "MARTINETSHIP" },
  { .first = "lineaged", .last = "LINEAGED" },
  { .first = "limosella", .last = "LIMOSELLA" },
  { .first = "centerer", .last = "CENTERER" },
  { .first = "unmuzzling", .last = "UNMUZZLING" },
  { .first = "measles", .last = "MEASLES" },
  { .first = "cyanurate", .last = "CYANURATE" },
  { .first = "gunsmithery", .last = "GUNSMITHERY" },
  { .first = "outcountry", .last = "OUTCOUNTRY" },
  { .first = "tuth", .last = "TUTH" },
  { .first = "dwelling", .last = "DWELLING" },
  { .first = "acetum", .last = "ACETUM" },
  { .first = "implicateness", .last = "IMPLICATENESS" },
  { .first = "eclegm", .last = "ECLEGM" },
  { .first = "scrapped", .last = "SCRAPPED" },
  { .first = "gastrocolotomy", .last = "GASTROCOLOTOMY" },
  { .first = "warsaw", .last = "WARSAW" },
  { .first = "parapsychism", .last = "PARAPSYCHISM" },
  { .first = "malapplication", .last = "MALAPPLICATION" },
  { .first = "burlily", .last = "BURLILY" },
  { .first = "bisphenoid", .last = "BISPHENOID" },
  { .first = "bipinnatifid", .last = "BIPINNATIFID" },
  { .first = "pinnation", .last = "PINNATION" },
  { .first = "loverliness", .last = "LOVERLINESS" },
  { .first = "unplough", .last = "UNPLOUGH" },
  { .first = "apnea", .last = "APNEA" },
  { .first = "querken", .last = "QUERKEN" },
  { .first = "unheroical", .last = "UNHEROICAL" },
  { .first = "giraffesque", .last = "GIRAFFESQUE" },
  { .first = "evasiveness", .last = "EVASIVENESS" },
};
